[ImageFormatControl]
WidthMax = 2048
HeightMax = 2048
RegionSelector = "Region0"
RegionDestination = "Stream0"
Width = 1024
Height = 1024
OffsetX = 0
OffsetY = 0
ReverseScanDirection = true
PixelFormat = "Mono8"
PixelSize = "Bpp8"
ImageCompressionMode = "Off"
ImageCompressionQuality = 90
TestPatternGeneratorSelector = "Sensor"
TestPattern = "Off"
FrameSpecInfoSelector = "Timestamp"
FrameSpecInfo = true

[AcquisitionControl]
AcquisitionMode = "SingleFrame"
ExposureMode = "Timed"
ExposureTime = 100
ExposureAuto = "Off"
AutoExposureTimeLowerLimit = 50
AutoExposureTimeUpperLimit = 1000
FrameTimeoutEnable = true
FrameTimeoutTime = 100

[AnalogControl]
Gain = 5
GainAuto = "Off"
AutoGainLowerLimit = 0
AutoGainUpperLimit = 20
ADCGainEnable = true
DigitalShift = 1
DigitalShiftEnable = true
Brightness = 50
BlackLevel = 0
BlackLevelEnable = true
BalanceWhiteAuto = "Off"
BalanceRatioSelector = "Red"
BalanceRatio = 128
Gamma = 2
GammaSelector = "sRGB"
GammaEnable = true
Hue = 0
HueEnable = true
Saturation = 100
SaturationEnable = true

[LUTControl]
LUTSelector = "Luminance"
LUTEnable = true
LUTIndex = 0
LUTValue = 128

[FrequencyConverterControl]
InputSource = "Line0"
SignalAlignment = "RisingEdge"
PreDivider = 1
Multiplier = 1
PostDivider = 1
