[[groups]]
group_name = "设备信息"
parameters = [
    { key = "设备类型", ref = "DeviceType", type = "enum", frequency = 0 },
    { key = "设备扫描类型", ref = "DeviceScanType", type = "enum", frequency = 0 },
    { key = "制造商名称", ref = "DeviceVendorName", type = "string", frequency = 0 },
    { key = "设备型号", ref = "DeviceModelName", type = "string", frequency = 0 },
    { key = "制造商信息", ref = "DeviceManufacturerInfo", type = "string", frequency = 0 },
    { key = "设备版本", ref = "DeviceVersion", type = "string", frequency = 0 },
    { key = "固件版本", ref = "DeviceFirmwareVersion", type = "string", frequency = 0 },
    { key = "设备序列号", ref = "DeviceSerialNumber", type = "string", frequency = 0 },
    { key = "设备标识", ref = "DeviceID", type = "string", frequency = 0 },
    { key = "设备运行时间", ref = "DeviceUptime", type = "integer", frequency = 1 },
    { key = "板卡类型", ref = "BoardDeviceType", type = "integer", frequency = 0 },
    { key = "连接速度", ref = "DeviceConnectionSpeed", type = "integer", frequency = 0 },
    { key = "链路速度", ref = "DeviceLinkSpeed", type = "integer", frequency = 5 },
    { key = "链路连接数量", ref = "DeviceLinkConnectionCount", type = "integer", frequency = 5 },
    { key = "最大吞吐量", ref = "DeviceMaxThroughput", type = "integer", frequency = 5 },
]
