[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
anyhow = { workspace = true }
crossbeam-channel = { workspace = true }

config = { workspace = true }
utility = { workspace = true }
