[camera]
exposure_auto = false
gain_auto = true

exposure_time = 1000.0 # us(微秒)
gain = 10.0            # dB(分贝)

height = 1080 # 图像高度
width = 1440  # 图像宽度

[detect]

[track]

[robot]

[gui]
video_fps = 30
