[package]
name = "detector"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { path = "../config" }
thiserror = { workspace = true }
libc = { workspace = true }
log = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }
cc = { workspace = true }

[features]
mindvision = []
hikvision = []
visualize = []
