[package]
name = "detector"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
libc = { workspace = true }

[build-dependencies]
bindgen = { workspace = true }
cc = { workspace = true }

[features]
default = ["hikvision"]
mindvision = []
hikvision = []
